### ISSUE TITLE
Game crashes while loading modpack (latest update)

### ISSUE THREAD

**Issue by Zmanitee** [dizzyd/Mekanism#28]
*Edit: sentence structure/irrelevant promting information
#### Issue description:
I am running a major modpack (currently at 62 mods, not including mekanism) and it doesn't even get past the loading screen of Minecraft. I've included the crash log below. vv

#### Steps to reproduce:
1. Download mekanism
2. Run Minecraft through MultiMC
3. Minecraft starts up, but crashes around stage 3 of its opening (not sure exactly, modpack takes a while to load so I don't always pay attention)

#### Version:
**Forge:** 14.23.5.2768 (1.12.2)
**Mekanism:** 1.12.2-9.5.0b2.jar
**Other relevant version:** 

#### Crashlog:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at mekanism.common.integration.wrenches.Wrenches.initialise(Wrenches.java:43)
	at mekanism.common.integration.MekanismHooks.hook(MekanismHooks.java:115)
	at mekanism.common.Mekanism.postInit(Mekanism.java:844)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
	at ic2.core.util.ConfigUtil.getBool(ConfigUtil.java:83)
	at ic2.core.item.tool.ItemToolWrench.<clinit>(ItemToolWrench.java:201)
	... 53 more

**Comment by dizzyd** [comment]
Hi @Zmanitee - could you please provide either the name of the modpack (if it's public) or the manifest.json? It looks like an interaction between IC2 and Mek, but is probably dependent on the version of IC2. :)

Thanks!

**Comment by Zmanitee** [comment]
Hey, @dizzyd! While the modpack is not public (it's mine) it does have a version of industrialcraft. Here is the version: industrialcraft-2-2.6.252-ex110

**Comment by pupnewfster** [comment]
That version of IC2 is for MC 1.10.2, that is probably your problem

**Comment by Zmanitee** [comment]
@pupnewfster oh haha, didn't realize. Thanks, all!
